name: GuestBook CI/CD Pipeline

env:
  DOCKER_REPOSITORY: yu3papa/cicd_guestbook

on:
  push:

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Maven Build (with JUnit)
      run: |
        ./mvnw clean test package

    - name: Upload Test-Result Report
      uses: actions/upload-artifact@v3
      with:
        name: Junit-Surefire_Report
        path: target/surefire-reports
        retention-days: 1

    - name: Set Docker Image Tag
      run: |
        echo "DOCKER_IMAGE_TAG=$(date +%Y%m%d%H%M%S)_$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Docker Image Build
      run: |
        docker image build --build-arg VERSION=$DOCKER_IMAGE_TAG --tag "$DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG" .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Image PUSH
      run: |
        docker image push $DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG
